export const tableData = document.getElementById("table-data")
export const loader = document.getElementById("loader")
export const year = document.getElementById("year")
export const tableBody = document.getElementById("table-body")
export const sortIcon = document.querySelectorAll(".sort-icon")