export const tableData = document.getElementById("table")
export const loader = document.getElementById("loader")
export const year = document.getElementById("year")
export const tableBody = document.getElementById("table-body")
export const sortBtnList =  document.querySelectorAll(".sort-btn")
export const sortIcon = document.querySelectorAll(".sort-icon")